data:
  filename: "WA_Fn-UseC_-Telco-Customer-Churn.csv"
  categorical_columns:
    - ContractType
    - InternetService
    - PaymentMethod
    - StreamingTV
    - StreamingMovies
    - PhoneService
    - Gender
  numerical_columns:
    - Tenure
    - MonthlyCharges
    - TotalCharges
    - SatisfactionScore

model:
  target: "Churn"
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  max_depth: 10
  class_weight: "balanced"

visualization:
  color_scheme: ["#2ecc71", "#e74c3c", "#3498db"]
  chart_theme: "plotly_white"
  categorical_palette: "Set3"
  correlation_colorscale: "RdBu"
  defaults:
    primary_color: "#2ecc71"
    secondary_color: "#e74c3c"
    neutral_color: "#3498db"
    background_color: "#ffffff"
